plugins {
    id 'java-library'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'auth'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // IMPORT THE BOM HERE - Replace '3.2.4' with the exact Spring Boot version used in your main :app module
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.2.4')

    // Spring Security
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // User module
    implementation project(':user')

    // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'


    // Spring Boot Starter Web (necessário para servlet)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Spring Boot Starter Data JPA (para @Transactional)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Jakarta Servlet API (caso precise explicitamente)
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'

}

tasks.named('test') {
    useJUnitPlatform()
}
