
spring:
  application:
    name: nutrition-daily
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrition_daily
    username: nutrition_user
    password: nutrition_password

  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true