spring.application.name=user-service

spring.datasource.url: jdbc:postgresql://localhost:5432/userdb
spring.datasource.username: user_service
spring.datasource.password: user_service


spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

